# Generated by Django 2.2.4 on 2019-08-07 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotissue',
            old_name='data',
            new_name='date',
        ),
    ]
