# Generated by Django 2.2.4 on 2019-08-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('price', models.FloatField()),
                ('category', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
