# Generated by Django 2.2.6 on 2019-10-23 00:55

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posting',
            old_name='user',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='posting',
            name='hastags',
        ),
        migrations.RemoveField(
            model_name='posting',
            name='like_users',
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=imagekit.models.fields.ProcessedImageField(upload_to='postings/images'),
        ),
        migrations.AlterField(
            model_name='image',
            name='posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='postings.Posting'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='HashTag',
        ),
    ]
